// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxogsengwwsebrvosxof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4b2dzZW5nd3dzZWJydm9zeG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODU3ODksImV4cCI6MjA2OTg2MTc4OX0.I9POMf4dz1rvwutNO0qbRbo3Qlqv-0zQVL3vuwheO6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});